[package]
name = "shroudforge-updater"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "shroudforge-updater"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
shroudforge-package.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }
