use crate::{EnumValueDefinition, FieldDefinition, GameSchema, TypeDefinition};
use serde::Serialize;
use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum SnapshotError {
    #[error("cannot create {0}: {1}")]
    Create(PathBuf, std::io::Error),
    #[error("cannot serialize {0}: {1}")]
    Serialize(&'static str, serde_json::Error),
    #[error("cannot write {0}: {1}")]
    Write(PathBuf, std::io::Error),
}

#[derive(Debug, Clone)]
pub struct SnapshotResult {
    pub directory: PathBuf,
    pub type_count: usize,
    pub field_count: usize,
}

#[derive(Serialize)]
struct Profile<'a> {
    game_version: &'a str,
    parser: &'a str,
    type_count: usize,
    field_count: usize,
    resource_type_count: usize,
}

/// Public name-based view. KFC lookup hashes remain an implementation detail of
/// the parser/serializer and are deliberately not published as mod API data.
#[derive(Serialize)]
struct PublicType<'a> {
    name: &'a str,
    impact_name: &'a str,
    qualified_name: &'a str,
    namespace: &'a [String],
    inner_type: &'a Option<String>,
    primitive: &'a str,
    size: u32,
    alignment: u16,
    element_alignment: u16,
    field_count: u32,
    fields: &'a BTreeMap<String, FieldDefinition>,
    enum_values: &'a BTreeMap<String, EnumValueDefinition>,
}

pub fn export_api_snapshot(
    schema: &GameSchema,
    root: impl AsRef<Path>,
) -> Result<SnapshotResult, SnapshotError> {
    let directory = root.as_ref().join(profile_id(&schema.game_version));
    fs::create_dir_all(&directory)
        .map_err(|error| SnapshotError::Create(directory.clone(), error))?;
    let field_count = schema.types.values().map(|value| value.fields.len()).sum();
    let profile = Profile {
        game_version: &schema.game_version,
        parser: &schema.parser,
        type_count: schema.types.len(),
        field_count,
        resource_type_count: schema.resources.len(),
    };
    write_json(directory.join("profile.json"), "profile", &profile)?;
    let public_types: BTreeMap<_, _> = schema
        .types
        .iter()
        .map(|(name, value)| {
            (
                name,
                PublicType {
                    name: &value.name,
                    impact_name: &value.impact_name,
                    qualified_name: &value.qualified_name,
                    namespace: &value.namespace,
                    inner_type: &value.inner_type,
                    primitive: &value.primitive,
                    size: value.size,
                    alignment: value.alignment,
                    element_alignment: value.element_alignment,
                    field_count: value.field_count,
                    fields: &value.fields,
                    enum_values: &value.enum_values,
                },
            )
        })
        .collect();
    write_json(directory.join("types.json"), "types", &public_types)?;
    write_json(
        directory.join("resources.json"),
        "resources",
        &schema.resources,
    )?;
    write_file(directory.join("types.lua"), generate_lua(schema).as_bytes())?;
    Ok(SnapshotResult {
        directory,
        type_count: schema.types.len(),
        field_count,
    })
}

fn write_json<T: Serialize>(
    path: PathBuf,
    name: &'static str,
    value: &T,
) -> Result<(), SnapshotError> {
    let bytes =
        serde_json::to_vec_pretty(value).map_err(|error| SnapshotError::Serialize(name, error))?;
    write_file(path, &bytes)
}

fn write_file(path: PathBuf, bytes: &[u8]) -> Result<(), SnapshotError> {
    fs::write(&path, bytes).map_err(|error| SnapshotError::Write(path, error))
}

fn profile_id(version: &str) -> String {
    let value: String = version
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect();
    format!("enshrouded-{}", value.trim_matches('-'))
}

fn generate_lua(schema: &GameSchema) -> String {
    let mut output = String::from("---@meta\n-- Generated by Shroudforge_Parser. Do not edit.\n\n");
    output.push_str("---@alias ShroudForgeQualifiedTypeName\n");
    for name in schema.types.keys() {
        let _ = writeln!(output, "---| {:?}", name);
    }
    output.push('\n');
    for definition in schema.types.values() {
        match definition.primitive.as_str() {
            "Struct" => append_struct(&mut output, definition, schema),
            "Enum" => append_enum(&mut output, definition),
            _ => {}
        }
    }
    output
}

fn append_struct(output: &mut String, definition: &TypeDefinition, schema: &GameSchema) {
    let _ = write!(output, "---@class {}", lua_name(&definition.qualified_name));
    if let Some(inner) = &definition.inner_type {
        let _ = write!(output, " : {}", lua_type(schema, inner));
    }
    output.push('\n');
    let _ = writeln!(
        output,
        "---@field __qualified_name {:?}",
        definition.qualified_name
    );
    for field in definition.fields.values() {
        let _ = writeln!(
            output,
            "---@field {} {} @ native offset 0x{:x}",
            field.name,
            lua_type(schema, &field.type_name),
            field.data_offset
        );
    }
    output.push('\n');
}

fn append_enum(output: &mut String, definition: &TypeDefinition) {
    let _ = writeln!(output, "---@alias {}", lua_name(&definition.qualified_name));
    for value in definition.enum_values.values() {
        let _ = writeln!(output, "---| {:?} # {}", value.name, value.value);
    }
    output.push('\n');
}

fn lua_type(schema: &GameSchema, name: &str) -> String {
    let Some(definition) = schema.types.get(name) else {
        return lua_name(name);
    };
    match definition.primitive.as_str() {
        "None" => "nil".into(),
        "Bool" => "boolean".into(),
        "UInt8" => "u8".into(),
        "SInt8" => "i8".into(),
        "UInt16" => "u16".into(),
        "SInt16" => "i16".into(),
        "UInt32" => "u32".into(),
        "SInt32" => "i32".into(),
        "UInt64" => "u64".into(),
        "SInt64" => "i64".into(),
        "Float32" => "f32".into(),
        "Float64" => "f64".into(),
        "BlobString" | "DsString" => "string".into(),
        "BlobArray" | "DsArray" | "StaticArray" => definition
            .inner_type
            .as_deref()
            .map(|inner| format!("{}[]", lua_type(schema, inner)))
            .unwrap_or_else(|| "unknown[]".into()),
        "BlobOptional" | "DsOptional" => definition
            .inner_type
            .as_deref()
            .map(|inner| format!("{}?", lua_type(schema, inner)))
            .unwrap_or_else(|| "unknown?".into()),
        "Typedef" => definition
            .inner_type
            .as_deref()
            .map(|inner| lua_type(schema, inner))
            .unwrap_or_else(|| lua_name(name)),
        _ => lua_name(name),
    }
}

fn lua_name(value: &str) -> String {
    value.replace("::", ".")
}
