import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, extname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const localeDirectory = resolve(root, 'src/locales')
const localeFiles = (await readdir(localeDirectory)).filter(file => extname(file) === '.json')
const flags = {}

for (const file of localeFiles) {
  const catalog = JSON.parse(await readFile(resolve(localeDirectory, file), 'utf8'))
  const code = String(catalog['locale.flag'] ?? '').toLowerCase()
  if (!/^[a-z]{2}$/.test(code)) throw new Error(`${file}: locale.flag must be a two-letter SVG country code`)
  flags[code] = await readFile(resolve(root, `node_modules/flag-icons/flags/4x3/${code}.svg`), 'utf8')
}

const output = `// Generated by scripts/generate-flags.mjs. Do not edit.\nconst flagSvgs: Record<string, string> = ${JSON.stringify(flags, null, 2)}\nexport default flagSvgs\n`
await writeFile(resolve(root, 'src/generated-flags.ts'), output)
console.log(`Generated ${Object.keys(flags).length} locale SVG flags.`)
